Sage-Bionetworks/mPower-2-iOS

- mPower2/mPower2.xcodeproj/project.pbxproj
- mPower2/mPower2/Assets.xcassets/AppIcon.appiconset/Contents.json
- mPower2/mPower2/MainViewController.swift
- mPower2/mPower2/Triggers.json
Note: This does **not** implement the changes that will be required within BridgeApp to track client data. That work is blocked until user sign-in is completed.
> Add triggers

- mPower2/MotorControl/StepObjects/MCTOverviewStepObject.swift
Requires: https://github.com/Sage-Bionetworks/BridgeApp-Apple-SDK/pull/17
> Refactor transformer

- mPower2/MotorControl/Resources/ActiveTaskSteps.storyboard
- mPower2/MotorControl/Resources/Tremor.json
- mPower2/MotorControl/Resources/Walk_And_Balance.json
- mPower2/MotorControl/ViewControllers/MCTInstructionStepViewController.swift
- mPower2/MotorControl/ViewControllers/MCTOverviewStepViewController.swift
- mPower2/MotorControlTests/NavigationTestObjects.swift
- mPower2/MotorControlTests/NavigationTests.swift
- mPower2/mPower2/AppDelegate.swift
- Add a view to the instruction step to make the background color behind the status bar correct when a placement type of topMarginBackground is used.
- Add the ability for the overview step to have placement types of topBackground and topMarginBackground.
- Fix icon titles not appearing on the overview step in tremor and tapping.
- Fix MCTHandStepController flipping images incorrect.
- Add unit tests for MCTHandStepController
- Fix image direction in active step in tremor.json
> Fix bugs in views, navigation, and tests

- mPower2/MotorControl/MCTTaskInfo.swift
- mPower2/MotorControl/Resources/ActiveTaskSteps.storyboard
- mPower2/MotorControl/Resources/Finger_Tapping.json
- mPower2/MotorControl/Resources/MotorControl.strings
- mPower2/MotorControl/Resources/TappingSectionStep.json
- mPower2/MotorControl/Resources/Tremor.json
- mPower2/MotorControl/Resources/TremorSectionStep.json
- mPower2/MotorControl/ViewControllers/MCTActiveStepViewController.swift
- mPower2/MotorControl/ViewControllers/MCTInstructionStepViewController.swift
- mPower2/MotorControlTests/Mock Objects/MotorControlTests-Bridging-Header.h
- mPower2/MotorControlTests/Mock Objects/NSLocale+UnitTest.m
- mPower2/MotorControlTests/NavigationTestObjects.swift
- mPower2/MotorControlTests/NavigationTests.swift
- mPower2/MotorControlTests/ResourceTests.swift
- mPower2/mPower2.xcodeproj/project.pbxproj
- mPower2/mPower2.xcodeproj/xcshareddata/xcschemes/MotorControl.xcscheme
- mPower2/mPower2.xcodeproj/xcshareddata/xcschemes/mPower2.xcscheme
Requires: https://github.com/Sage-Bionetworks/BridgeApp-Apple-SDK/pull/18
> Update JSON to use transformers

- mPower2/mPower2/AppDelegate.swift
Requires: https://github.com/Sage-Bionetworks/BridgeApp-Apple-SDK/pull/19
> Setup bridge

- mPower2/MotorControlTests/NavigationTestObjects.swift
Requires: https://github.com/Sage-Bionetworks/BridgeApp-Apple-SDK/pull/21
> Update the Bridge pointer and fix the tests.

- mPower2/MotorControl/Resources/ActiveTaskSteps.storyboard
- mPower2/MotorControl/Resources/Tremor.json
- mPower2/MotorControl/Resources/Walk_And_Balance.json
- mPower2/MotorControl/Views/MCTTapButton.swift
- Fix completion step image scaling.
- Fix tapping completion step layout and scaling.
- Update spoken instructions on walk and balance and tremor.
- Update walk and balance progress markers.
- Localize tap button title on tapping active step.
> Fix bugs with completion steps, and progress markers

- mPower2/MotorControl/MotorControl.h
- mPower2/MotorControl/Resources/ActiveTaskSteps.storyboard
- mPower2/MotorControl/ViewControllers/MCTActiveStepViewController.swift
- mPower2/MotorControlTests/Mock Objects/NSLocale+UnitTest.h
- mPower2/MotorControlTests/NavigationTestObjects.swift
- mPower2/mPower2.xcodeproj/project.pbxproj
- mPower2/mPower2/MainViewController.swift
- mPower2/mPower2/UIColor+mPowerTheme.swift
- mPower2/mPower2Tests/ResourceTests.swift
Requires: https://github.com/Sage-Bionetworks/BridgeApp-Apple-SDK/pull/27
> Rename ResearchStack2 -> Research

- mPower2/mPower2.xcodeproj/project.pbxproj
- mPower2/mPower2/AppDelegate.swift
- mPower2/mPower2/Info.plist
- mPower2/mPower2/SignIn.json
- mPower2/mPower2/UIColor+mPowerTheme.swift
Moved some files around and stubbed out the logic for displaying the sign in if not authorized.
Requires: https://github.com/Sage-Bionetworks/BridgeApp-Apple-SDK/pull/33
> Move the logic for sign in to the app delegate.

- mPower2/MotorControl/Resources/Walk_And_Balance.json
Clarify the language on the steps having to do with putting the phone in a pocket to allow the phone to be placed in the waistband of the user’s pants as well.
> Update the copy for the walk and balance test

- mPower2/mPower2/ConsentViewController.swift
-web site passes back json object, not string
-don’t forget to hook up the content controller to the script message handler, derp
> fix consent web view

- mPower2/mPower2/StudyBurstScheduleManager.swift
- mPower2/mPower2TestApp/ActivityManager.swift
@joshbruhin 
With this PR, you should be good to go for adding the study burst view. You can use the StudyBurstScheduleManager on the TodayViewController as the data source.
> Add storing a shuffled task order for the order in which the tasks should be active.

- mPower2/mPower2/DataSourceManager.swift
- mPower2/mPower2/StudyBurstScheduleManager.swift
- mPower2/mPower2/View Controllers/TaskBrowserViewController.swift
- mPower2/mPower2TestApp/ActivityManager.swift
Requires: https://github.com/Sage-Bionetworks/BridgeApp-Apple-SDK/pull/44
>  Update init method for activity groups

- mPower2/mPower2/PhoneRegistrationViewController.swift
- mPower2/mPower2/RegistrationWaitingViewController.swift
- mPower2/mPower2/SignInTaskViewController.swift
- mPower2/mPower2/mPower2.strings
on the “waiting for an SMS” view
> Implement changing phone number

- mPower2/mPower2.xcodeproj/project.pbxproj
- mPower2/mPower2/Base.lproj/Main.storyboard
- mPower2/mPower2/VersionLabel.swift
for when reporting bugs/issues
> Add version/build info to Profile tab placeholder

- mPower2/mPower2/SignIn.json
> add phone number “validation”

- mPower2/mPower2/Base.lproj/Main.storyboard
Remove the history and insights tabs from the main screen.
> IA-700 Hide the History and Insights tabs

- mPower2/mPower2/ExternalIDRegistrationViewController.swift
- mPower2/mPower2/SignInTaskViewController.swift
- mPower2/mPower2/StudyBurstScheduleManager.swift
Should be assigning to one of each pair of engagement data groups:
gr_SC_DB or gr_SC_CS
gr_BR_AD or gr_BR_II
gr_ST_T or gr_ST_F
gr_DT_F or gr_DT_T
see https://docs.google.com/document/d/1mvhpWl6aCZiXcV0nH48vwskybk7l70PzB4RyD9ZPqsI/edit#heading=h.hec7c3kf5vom
> IA-724 Change assignment of engagement data groups

- mPower2/MotorControl/Resources/Finger_Tapping.json
- mPower2/MotorControl/Resources/Tremor.json
- mPower2/mPower2/Medication.json
- mPower2/mPower2/SignIn.json
- mPower2/mPower2/StudyBurstReminder.json
Requires: https://github.com/Sage-Bionetworks/BridgeApp-Apple-SDK/pull/75
> Refactor JSON to match new input field “type” schema

- mPower2/MotorControl/ViewControllers/MCTActiveStepViewController.swift
- mPower2/mPower2/PhoneRegistrationViewController.swift
- mPower2/mPower2/SignInTaskViewController.swift
Update pointer and fix the immutable step navigation.
> Immutable next step identifier

- mPower2/mPower2/SignIn.json
to better fit on a 5S. Fixes IA-677.
> tweak phone signup text & placeholder

- mPower2/mPower2.xcodeproj/project.pbxproj
- mPower2/mPower2/AppDelegate.swift
- mPower2/mPower2/Base.lproj/Medication.json
- mPower2/mPower2/MP2ReminderManager.swift
- mPower2/mPower2/StudyBurstScheduleManager.swift
- mPower2/mPower2Tests/StudyBurstTests.swift
Requires: https://github.com/Sage-Bionetworks/BridgeApp-Apple-SDK/pull/85
> Meds reminders

- .travis.yml
This reverts commit f8884a97dc46c1e7ad4370a8cfb028d5567f1cc3.
> Revert "cat the full log on failure"

- mPower2/mPower2.xcodeproj/project.pbxproj
new profiles were created trying to fix certificate issues relating
to https://github.com/fastlane/fastlane/issues/13186
> new profiles

- mPower2/mPower2/DataSourceManager.swift
- mPower2/mPower2/StudyBurstScheduleManager.swift
- mPower2/mPower2/TodayScheduleManager.swift
- mPower2/mPower2TestApp/ActivityManager.swift
- mPower2/mPower2TestApp/AppDelegate.swift
- mPower2/mPower2TestApp/ParticipantManager.swift
- mPower2/mPower2Tests/StudyBurstTests.swift
- mPower2/mPower2Tests/TodayScheduleManagerTests.swift
Requires: https://github.com/Sage-Bionetworks/BridgeApp-Apple-SDK/pull/88
> Refactor to get client data from reports

- mPower2/mPower2/RegistrationWaitingViewController.swift
- mPower2/mPower2/SignInTaskViewController.swift
> Fix change-phone-number bug

- mPower2/mPower2.xcodeproj/project.pbxproj
- mPower2/mPower2/Base.lproj/Main.storyboard
- mPower2/mPower2/SurveyViewController.swift
- mPower2/mPower2/TabBarViewController.swift
Requires: https://github.com/Sage-Bionetworks/BridgeApp-Apple-SDK/pull/94
> Add hidden tab for viewing all surveys included in the AppConfig

- mPower2/mPower2/Base.lproj/consent.html
- mPower2/mPower2/DataSourceManager.swift
- mPower2/mPower2/WithdrawalViewController.swift
also enabling options for MPOW-144 depending how that shakes out.
requires https://github.com/Sage-Bionetworks/Bridge-iOS-SDK/pull/216
requires https://github.com/Sage-Bionetworks/BridgeApp-Apple-SDK/pull/95
> Fix for IA-773

- mPower2/MotorControl/ResultObjects/MCTTappingResultObject.swift
- mPower2/MotorControl/ViewControllers/MCTTappingCompletionStepViewController.swift
- mPower2/MotorControl/ViewControllers/MCTTappingStepViewController.swift
@Robert-Kolmos Please review changes and update Android to match. Thanks!
> Update the tapping test to include the same “tap count” feedback for test and results

- mPower2/MotorControl/Resources/Walk_And_Balance.json
¯\_(ツ)_/¯
https://sagebionetworks.jira.com/browse/IA-775
> Change wording for the balance long description.

- mPower2/mPower2.xcodeproj/project.pbxproj
- mPower2/mPower2/Base.lproj/SignIn.json
- mPower2/mPower2/Licenses.html
- mPower2/mPower2/mPower2/Base.lproj/PhoneLearnMore.html
requires https://github.com/Sage-Bionetworks/BridgeApp-Apple-SDK/pull/98
fixes IA-780
> Update phone signin copy

- mPower2/mPower2/MP2BridgeConfiguration.swift
- mPower2/mPower2/MP2Factory.swift
- mPower2/mPower2/ProfileTableItems.swift
- mPower2/mPower2/ProfileTableViewController.swift
requires https://github.com/Sage-Bionetworks/BridgeApp-Apple-SDK/pull/102
> Profile refactor per PR comments

- mPower2/mPower2/Base.lproj/SignIn.json
- shorter text so entry field isn’t below the fold
- dark background throughout
> phone signin screen updates

- mPower2/mPower2/AppDelegate.swift
- mPower2/mPower2/StudyBurstScheduleManager.swift
- mPower2/mPower2TestApp/ActivityManager.swift
- mPower2/mPower2TestApp/AppDelegate.swift
- mPower2/mPower2Tests/StudyBurstTests.swift
Fixes https://sagebionetworks.jira.com/browse/IA-794
Note: this issue was *not* introduced with refactoring work and is present in 2.0 stable.
> Fix study burst

- .travis.yml
- mPower2/mPower2/AppDelegate.swift
- mPower2/mPower2/PassiveCollectors.swift
requires https://github.com/Sage-Bionetworks/BridgeApp-Apple-SDK/pull/112
> Passive gait collection

- mPower2/mPower2/PassiveCollectors.swift
for when we get pause callbacks in the background
> use a bg task when setting a region

- mPower2/mPower2/AppDelegate.swift
- mPower2/mPower2TestApp/AppDelegate.swift
Note: this does not resolve all of the UI issues with mPower, but it establishes the color palette to use for those elements.
> Update color palette to target latest designs

- Cartfile
- Cartfile.resolved
- mPower2/mPower2/PassiveCollectors.swift
- mPower2/mPower2/ProfileTableViewController.swift
- mPower2/mPower2/View Controllers/PassiveDataPermissionStepViewController.swift
requires https://github.com/Sage-Bionetworks/Bridge-iOS-SDK/pull/230 and https://github.com/Sage-Bionetworks/BridgeApp-Apple-SDK/pull/130
> Passive permission archiving

- mPower2/mPower2/Info.plist
required by iOS 10 and earlier
> Add NSLocationAlwaysUsageDescription string

- mPower2/mPower2/Base.lproj/Main.storyboard
- mPower2/mPower2/Base.lproj/Medication.json
- mPower2/mPower2/TodayScheduleManager.swift
- mPower2/mPower2/View Controllers/TrackedItemsIntroductionStepViewController.swift
- mPower2/mPower2TestApp/Mock Responses/AppConfig.json
- mPower2/mPower2TestApp/ParticipantManager.swift
- mPower2/mPower2Tests/TodayScheduleManagerTests.swift
Note: this does not include pointing to an updated version of BridgeApp or SageResearch. That can be done in a separate PR.
> Assorted fixes discovered during meds refactor

- Cartfile.resolved
- mPower2/mPower2/TaskGroupScheduleManager.swift
- mPower2/mPower2TestApp/ActivityManager.swift
- mPower2/mPower2TestApp/AppDelegate.swift
Requires: https://github.com/Sage-Bionetworks/BridgeApp-Apple-SDK/pull/141
> Hook up asking about adding medications before active tasks

- Cartfile
- Cartfile.resolved
- mPower2/mPower2.xcodeproj/project.pbxproj
- mPower2/mPower2/AppDelegate.swift
- mPower2/mPower2/HistoryDataManager.swift
- mPower2/mPower2/HistoryFeedTableViewController.swift
- mPower2/mPower2/MP2Factory.swift
- mPower2/mPower2/MP2ReminderManager.swift
- mPower2/mPower2/Model/PassiveDataPermissionStepObject.swift
- mPower2/mPower2/Model/TrackedItemsIntroductionStepObject.swift
- mPower2/mPower2/PassiveCollectors.swift
- mPower2/mPower2/SurveyViewController.swift
- mPower2/mPower2/TaskGroupScheduleManager.swift
- mPower2/mPower2/TodayScheduleManager.swift
- mPower2/mPower2/View Controllers/GreatJobViewController.swift
- mPower2/mPower2/View Controllers/PassiveDataPermissionStepViewController.swift
- mPower2/mPower2/View Controllers/ProfileItemEditViewController.swift
- mPower2/mPower2/View Controllers/ReminderTableStepViewController.swift
- mPower2/mPower2/View Controllers/StudyBurstCompletionViewController.swift
- mPower2/mPower2/View Controllers/TrackedItemsIntroductionStepViewController.swift
- mPower2/mPower2/WithdrawalViewController.swift
This includes fixing the imports to import the BridgeAppUI and/or DataTracking frameworks.
> Update to BridgeApp 3.0

- Cartfile
- Cartfile.resolved
- mPower2/mPower2/Base.lproj/Main.storyboard
- mPower2/mPower2/Base.lproj/consent.html
- mPower2/mPower2/Info.plist
- mPower2/mPower2/MP2ProfileSection.swift
- mPower2/mPower2/PassiveCollectors.swift
- mPower2/mPower2/ProfileTableFooterView.xib
- mPower2/mPower2/ProfileTableHeaderView.xib
- mPower2/mPower2/ProfileTableItems.swift
- mPower2/mPower2/ProfileTableViewController.swift
- mPower2/mPower2/mPower2.strings
Requires https://github.com/Sage-Bionetworks/BridgeApp-Apple-SDK/pull/142 — don’t merge without first updating BridgeApp-Apple-SDK submodule pointer & min version in Cartfile after that PR is reviewed/approved/merged to stable.
> MP2-102 profile facelift

- Cartfile.resolved
- mPower2/mPower2/Base.lproj/Main.storyboard
- mPower2/mPower2/StudyBurstScheduleManager.swift
Been a while since I've run this on device over a slow WIFI connection. Found some peanuts.
> Fix assorted issues

- Cartfile.resolved
- mPower2/mPower2/Profile/ProfileTableFooterView.swift
- mPower2/mPower2/Profile/ProfileTableHeaderView.swift
- mPower2/mPower2/ProfileTableFooterView.xib
- mPower2/mPower2/ProfileTableHeaderView.xib
- mPower2/mPower2/ProfileTableViewController.swift
Currently, shows the whole survey (with the exception of the intro screen) whenever the user taps on one of the demographics survey questions.
Note: By using the` instantiateTaskViewModel` method, the manager will set itself as the task data manager and set up for updating data groups. Both of which are required to fully implement the functionality of the demographics surveys.
> Profile surveys

- mPower2/mPower2/ProfileTableItems.swift
- mPower2/mPower2/mPower2.strings
to use actual values
also update carthage dependencies
> wire up reminder settings displays

- Cartfile.resolved
Update pointer to include spoken warning that the pause button has been tapped to walk and balance countdowns.
> Update Cartfhage pointers

- Cartfile.resolved
- mPower2/mPower2/HistoryDataManager.swift
- mPower2/mPower2/HistoryItem+Custom.swift
Requires https://github.com/Sage-Bionetworks/BridgeApp-Apple-SDK/pull/164
https://sagebionetworks.jira.com/browse/MP2-254
https://sagebionetworks.jira.com/browse/MP2-255
https://sagebionetworks.jira.com/browse/MP2-256
Do not merge until travis passes the BridgeApp and pointers are updated. Thanks
> Bug fixes in data tracking and history feed

- mPower2/mPower2/ProfileTableViewController.swift
Use an alert popover to allow editing the participant’s name
> MP2-221 Edit participant’s name

- mPower2/mPower2/Base.lproj/Main.storyboard
- mPower2/mPower2/ProfileTableViewController.swift
and allow multi-line title & detail text
> Match new Profile table cell layouts

- Cartfile
- Cartfile.resolved
- mPower2/mPower2/HistoryDataManager.swift
- mPower2/mPower2/ProfileTableItems.swift
- mPower2/mPower2/ProfileTableViewController.swift
- mPower2/mPower2/StudyBurstScheduleManager.swift
- mPower2/mPower2/View Controllers/ProfileItemEditViewController.swift
Updates to include changes to Profile and fix for displaying the study burst reminder.
This does *not* include the medication reminder.
> Study burst reminder time

- Cartfile
- Cartfile.resolved
- mPower2/mPower2/MP2ReminderManager.swift
- mPower2/mPower2/ProfileTableItems.swift
- mPower2/mPower2/ProfileTableViewController.swift
Requires: https://github.com/Sage-Bionetworks/BridgeApp-Apple-SDK/pull/168
> Hook up display of the medication reminder step

- Cartfile.resolved
- mPower2/mPower2/DataSourceManager.swift
- mPower2/mPower2/mPower2.strings
https://sagebionetworks.jira.com/browse/MP2-273
https://sagebionetworks.jira.com/browse/MP2-272
> Includes fixes and changes from this week

- Cartfile.resolved
- mPower2/mPower2/PassiveCollectors.swift
Requires https://github.com/Sage-Bionetworks/Bridge-iOS-SDK/pull/250
> Fix passive geofence spam

- fastlane/Fastfile
move fastlane setup_travis to before_all section
> build fix attempt

- mPower2/mPower2/Custom Views/ProgressCircleView.swift
- mPower2/mPower2/DataSourceManager.swift
- mPower2/mPower2/MP2ReminderManager.swift
- mPower2/mPower2/StudyBurstScheduleManager.swift
- mPower2/mPower2/View Controllers/StudyBurstViewController.swift
- mPower2/mPower2/View Controllers/TaskBrowserViewController.swift
- mPower2/mPower2TestApp/AppDelegate.swift
Bit of a hack, but apparently the only way to do a 90 day repeat is to listen for the notification to fire and add a replacement notification for 90 days out. ¯\_(ツ)_/¯ 
Also updated to SageResearch 3
> Update to SageResearch 3 and add 90 day repeat of study burst notification.

- mPower2/mPower2/StudyBurstScheduleManager.swift
- mPower2/mPower2/View Controllers/StudyBurstViewController.swift
- mPower2/mPower2/mPower2.strings
Will create a clone of the JIRA for Android.
> MP2-139 Update study burst messaging

- mPower2.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings
-update to current Bridge-iOS-SDK master
-share setting to use legacy build system in workspace
> Get it to build in Xcode 12

- Cartfile.resolved
- mPower2/mPower2/AppDelegate.swift
- mPower2/mPower2/DataSourceManager.swift
- mPower2/mPower2/SignInTaskViewController.swift
- mPower2/mPower2/View Controllers/StudyBurstViewController.swift
also update mPower 2 code to work with resolved BridgeApp/SageResearch lib versions
> Auto-detect carrier’s country code
